apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iris-classifier
  namespace: ml-ops
spec:
  chart:
    spec:
      chart: iris-classifier
  values:
    image:
      tag: v1.1.0