apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
  - ../../../../applications/namespace/v1/
  - ../../../../applications/ingress/v4.12.2-v1/
# patches:
#   - path: values.yaml
#     target:
#       kind: HelmRelease
#       name: ngress-nginx